
# Central conversation state constants (
    integers)
(
    ASK_PICKUP_TYPE,
    WAITING_PICKUP_CATEGORY,
    WAITING_PICKUP_LOCATION,
    ASK_DROPOFF_TYPE,
    WAITING_DROPOFF_CATEGORY,
    WAITING_DROPOFF_LOCATION,
    ASK_DATE,
    WAITING_DATE,
    ASK_TIME,
    WAITING_TIME,
    ASK_PASSENGER_COUNT,
    WAITING_NAME,
    WAITING_PHONE,
    ASK_BABY_SEAT,
    WAITING_BABY_SEAT,
    WAITING_NOTES,
    SHOW_SUMMARY,
    WAITING_CONFIRMATION,,
    ASK_FLIGHT_NUMBER,
    WAITING_FLIGHT_NUMBER,
    ASK_MEETING_TIME,
    WAITING_MEETING_TIME,
) = range(26)
